### PR TITLE
Fix issue building on latest MacOS 12.1 with Apple Silicon.

### PR DESCRIPTION
**Pull request by chrismoos**
Security framework added to linker flags due to build error:

```
Undefined symbols for architecture arm64:
  "_SecTaskCopyValueForEntitlement", referenced from:
      _darwin_detach_kernel_driver in libusb-1.0.a(darwin_usb.o)
  "_SecTaskCreateFromSelf", referenced from:
      _darwin_detach_kernel_driver in libusb-1.0.a(darwin_usb.o)
ld: symbol(s) not found for architecture arm64
```

### CODE REVIEW

**Comment by grayfox-dev** [comment]
Can confirm that this also worked for my x86 Mac. Thanks for this!

**Comment by tommythorn** [comment]
Can confirm that this fixed the build on macOS 15.1.1 w/Apple Silicon
@kost can we have this pulled please?
